/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.codeli4m.lab5ejercicio2;

import javax.swing.table.DefaultTableModel;
import java.text.DecimalFormat;
/**
 *
 * @author HP
 */
public class Gui extends javax.swing.JFrame {
    DefaultTableModel empleadosTableModel;
    /**
     * Creates new form Gui
     */
    public Gui() {
        initComponents();
        initEmpleadosTableModel();
    }

    public void initEmpleadosTableModel(){
        Object[] columnNames = { "Nombres", "Genero", "Salario" };
        Object[][] sampleData = { {"Carmen","F","1400"},{"Efrain","M","1300"},{"Luis","M","2000"} };
        this.empleadosTableModel = new DefaultTableModel(sampleData, columnNames);
        this.jTableEmpleados.setModel(empleadosTableModel);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldSalario = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jComboBoxGender = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableEmpleados = new javax.swing.JTable();
        jButtonVerReporte = new javax.swing.JButton();
        jButtonAgregar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 22)); // NOI18N
        jLabel1.setText("GESTION DE EMPLEADOS");

        jLabel2.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        jLabel2.setText("Nombre");

        jTextFieldNombre.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        jTextFieldNombre.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 8, 2, 8));

        jLabel3.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        jLabel3.setText("Salario");

        jTextFieldSalario.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        jTextFieldSalario.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 8, 2, 8));

        jLabel4.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        jLabel4.setText("Genero");

        jComboBoxGender.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        jComboBoxGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Femenino" }));

        jTableEmpleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nombre", "Genero", "Salario"
            }
        ));
        jScrollPane1.setViewportView(jTableEmpleados);

        jButtonVerReporte.setBackground(java.awt.Color.green);
        jButtonVerReporte.setFont(new java.awt.Font("Roboto", 1, 15)); // NOI18N
        jButtonVerReporte.setForeground(java.awt.Color.black);
        jButtonVerReporte.setText("REPORTE");
        jButtonVerReporte.setBorder(null);
        jButtonVerReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVerReporteActionPerformed(evt);
            }
        });

        jButtonAgregar.setBackground(java.awt.Color.blue);
        jButtonAgregar.setFont(new java.awt.Font("Roboto", 1, 15)); // NOI18N
        jButtonAgregar.setForeground(java.awt.Color.white);
        jButtonAgregar.setText("AGREGAR");
        jButtonAgregar.setBorder(null);
        jButtonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jTextFieldSalario, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jComboBoxGender, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButtonVerReporte, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(108, 108, 108))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxGender, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldSalario, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonVerReporte, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarActionPerformed
        // TODO add your handling code here:
        String nombre = jTextFieldNombre.getText();
        String genderSelection = jComboBoxGender.getSelectedItem().toString();
        String gender = genderSelection.equalsIgnoreCase("MASCULINO") ? "M" : "F";
        String salario = jTextFieldSalario.getText();
        
        String[] dataToInsert = new String[3];
        dataToInsert[0] = nombre;
        dataToInsert[1] = gender;
        dataToInsert[2] = salario;
        this.empleadosTableModel.addRow(dataToInsert);
    }//GEN-LAST:event_jButtonAgregarActionPerformed

    private void jButtonVerReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVerReporteActionPerformed
        // TODO add your handling code here:
    DecimalFormat df = new DecimalFormat("0.00");

    // a) La cantidad de personas que ganan más de 850 al mes.
    // b) El promedio de salarios.
    // c) El porcentaje de mujeres que trabajan en esa empresa
    // d) El porcentaje de varones que trabajan en esa empresa
    // nombre, genero, salario
        int cantidadPersonasMas850 = 0;
        int cantidadFemenino = 0;
        int cantidadMasculino = 0;
        int sumaSalarios = 0;
        int gimnasioTableRowCount = this.empleadosTableModel.getRowCount();
        for (int i=0;i<gimnasioTableRowCount;i++){
            String gender1 = this.empleadosTableModel.getValueAt(i, 1).toString();
            String salario1 = this.empleadosTableModel.getValueAt(i, 2).toString();
            int salario = Integer.parseInt(salario1);
            System.out.println("SALARIO");
            System.out.println(salario);
            System.out.println("GENDER");
            System.out.println(gender1);
            sumaSalarios += salario;
            if (salario > 850){
                cantidadPersonasMas850 += 1;
            }
            if (gender1.equalsIgnoreCase("F")){
                cantidadFemenino += 1;
            }else{
                cantidadMasculino += 1;
            }
        }
        
        System.out.println("cantidadPersonasMas850");
        System.out.println(cantidadPersonasMas850);
        int promedioSalarios = sumaSalarios / gimnasioTableRowCount;
        int cantidadTotal = cantidadFemenino + cantidadMasculino;
        double porcentajeMujeres = (cantidadFemenino * 100.0)/cantidadTotal;
        double porcentajeVarones = (cantidadMasculino * 100.0)/cantidadTotal;
        
        
        Reporte interfaceReporte = new Reporte();
        interfaceReporte.fillCantidadPersonasGananMasDe850(String.valueOf(cantidadPersonasMas850));
        interfaceReporte.fillDistribucionPorcentualGenero(String.valueOf(df.format(porcentajeVarones)), String.valueOf(df.format(porcentajeMujeres)));
        interfaceReporte.fillPromedioSalarios(String.valueOf(promedioSalarios));
        interfaceReporte.setVisible(true);
    }//GEN-LAST:event_jButtonVerReporteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAgregar;
    private javax.swing.JButton jButtonVerReporte;
    private javax.swing.JComboBox<String> jComboBoxGender;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableEmpleados;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldSalario;
    // End of variables declaration//GEN-END:variables
}
